#!/usr/bin/env ruby
require 'open-uri'

unless ARGV.length == 1
    puts "Usage: swiftGitInit.rb repoDir"
    exit
end

repo_dir  = ARGV[0]
Dir.chdir(repo_dir)
puts "Moved to #{repo_dir}"
`git init`
puts "Git initialized"

gitignore_uri = "https://raw.githubusercontent.com/github/gitignore/master/Swift.gitignore"
gitignore_file = File.new( ".gitignore", "w+")
bytes = gitignore_file.write(open(gitignore_uri).read)
gitignore_file.close
puts "Gitignore file created"
`git add .gitignore -v`
`git commit -m "Added gitignore"`
puts "Gitignore committed"
`git add .`
`git commit -m "First commit"` 
puts "First commit"
puts "Done"




