#!/bin/sh
#Generates a tag file with indexing every module accessible to the current installation of python. See (https://www.fusionbox.com/blog/detail/navigating-your-django-project-with-vim-and-ctags/590/)
echo '\n -- Generating ctags file for all python modules --\n'
ctags -R --fields=+l --languages=python --python-kinds=-iv -f ~/Development/tags/python.tags $(python -c "import os, sys; print( ' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))")

